clip:
  boundary: "../../data/boundary/sandiego/MGRA13.shp"
  boundary_two: "../../data/boundary/scag/SCAG_TAZ.geojson"
  alllinks_processed: "../../data/july2021/all_links.csv" #processed links and nodes file for whole California
  alllinks_processed_geom: "../../data/july2021/alllinksgeom_gdf.shp"
  allnodes_processed: "../../data/july2021/all_nodes.csv"
  allnodes_popdensity: ""

write:
  cityname: "sandiego"
  cityname_two: "scag"
  links_filename: "links.csv"
  nodes_filename: "nodes.csv"
 

popdensity:
  raster: "../../data/popdensity    "
  popdensity_filename : "popdensity.csv"





  
